// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface DeleteCompteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCompteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the compte to delete
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <pre>
   * ID of the compte to delete
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
